### ISSUE TITLE
Search by stars and/or time  

### ISSUE THREAD

**Issue by JeffreySarnoff** [djsegal/julia_observer#10]
It would help to have a way to search for packages that have n+ and m-n stars, similarly for months past.

**Comment by djsegal** [comment]
Sorry, was adding a news feed. Will get to this soon. 

Probably solving this by putting star & date filters into a settings modal (backed by cookies)

**Comment by djsegal** [comment]
resolved by: https://github.com/djsegal/julia_observer/commit/63cd7cbc0497840a7267059fd224d7e1f46b2524

does this work as expected?

------

instructions: 

+ go to drop down in navbar
+ click settings
+ adjust min/max star or start/end date to heart's content

**Comment by djsegal** [comment]
closing. 

-------

@JeffreySarnoff feel free to reopen this if it doesn't work as expected

**Comment by djsegal** [comment]
@JeffreySarnoff, just checking in. what do you think of this feature?

**Comment by JeffreySarnoff** [comment]
I like the effort.  It is an improvement.

**Comment by JeffreySarnoff** [comment]
Yes it does! Thank you.
