### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by JeffreySarnoff** [djsegal/julia_observer#102]
The recent activity charts are not available until a package has been selected to be the focus.
It would be helpful to have a time_from_last_commit appear in parens following a package's name, where the package names first appear in a vertical list.

|  *search term*  |
|--------------------------|
  |MyPackage (1mo)|
|AnotherPackage (19mo)|

**Comment by djsegal** [comment]
Would this only be in a search dropdown?

Or do you want this anywhere there is already a stars icon (with the # of github stars)?

**Comment by JeffreySarnoff** [comment]
both, please (I will be happy with any though)

**Comment by djsegal** [comment]
As a first pass, I added an "updated at" tooltip as a hover on packages in the list.

Does this work well enough? Also, "HOT" sorting sorts by this

**Comment by JeffreySarnoff** [comment]
gr8, thank you
