### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by tkoolen** [djsegal/julia_observer#105]
The following packages appear to be missing:

* RigidBodyDynamics
* RigidBodySim
* Parametron
* OSQP

**Comment by tkoolen** [comment]
Seems to have been resolved. Thanks!

**Comment by djsegal** [comment]
I didn't do anything :/

Have a feeling there was a caching issue involved

**Comment by baggepinnen** [comment]
I also have some packages that have always been missing from julia observer.
- MonteCarloMeasurements.jl 
- ThreadTools.jl 

MonteCarloMeasurements.jl has been registered for over a year but has never been found on juliaobserver

**Comment by djsegal** [comment]
The original problem was fixed. Those two packages are now involved in djsegal/julia_packages#44
