### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by ronisbr** [djsegal/julia_observer#107]
Hi guys!

It seems that all of my packages are missing:

* [SatelliteToolbox.jl](https://github.com/JuliaSpace/SatelliteToolbox.jl)
* [ReferenceFrameRotations.jl](https://github.com/JuliaSpace/ReferenceFrameRotations.jl)
* [PrettyTables.jl](https://github.com/ronisbr/PrettyTables.jl)

**Comment by djsegal** [comment]
Related to: djsegal/julia_packages#107 

// they should be fixed in tandem
