### ISSUE TITLE
search broken?

### ISSUE THREAD

**Issue by RossBoylan** [djsegal/julia_observer#109]
When I first open https://juliaobserver.com (using FF) I see a list of top packages.

But when I type something in the search box, even the name of a package already shown, the list of packages goes blank.

Similarly, if I select one of the categories on the right, the list of packages goes blank.

**Comment by djsegal** [comment]
closing. related to: djsegal/julia_observer#107 and djsegal/julia_observer#108 

// making another issue to help prevent this failure mode in the future
