### ISSUE TITLE
Display time of most recent update

### ISSUE THREAD

**Issue by catawbasam** [djsegal/julia_observer#11]

**Comment by djsegal** [comment]
You mean the last time the server updated everything?

Not the last time packages were updated, right?

**Comment by djsegal** [comment]
Also, do you have any preference where it would go?

I'm having a little difficulty choosing what spot is unobtrusive enough, yet still easily found

**Comment by catawbasam** [comment]
Thanks for taking a look.  My preference would be on the top blue bar just
above the Top New A-Z and Hot selections.
cheers,
Keith

**Comment by djsegal** [comment]
Resolved by: https://github.com/djsegal/julia_observer/commit/b6bb3bc921329dd230ebed8b5693a08e38fed2c5

`Updated at` shown at bottom of settings modal (accessed from the navbar's dropdown)

**Comment by catawbasam** [comment]
Thanks!
