### ISSUE TITLE
Single github API failure can lead to broken site

### ISSUE THREAD

**Issue by djsegal** [djsegal/julia_observer#110]
Don't know the exact origin of:
+ #107 
+ #108 
+ #109 

But it seems like a single github api request was mis-hit and brought down the whole julia observer website.

// hope to have a better handle on this next time it happens and prevent it occurring afterwards

**Comment by Marc-Cox-08** [comment]
Whoops...

Something went wrong.

Let us know so we can try to fix it.

**Comment by djsegal** [comment]
The way I've been fixing this (after resolving whatever issue actually caused it) is by:
+ Locating a package I know exists
+ Finding the first version of it where a `Batch` id is present

Could make a way to never update to a batchless state

// at the end, sort of a trade-off between hard failing and soft failing
