### ISSUE TITLE
Trouble finding my package in top packages categories

### ISSUE THREAD

**Issue by gtollefson** [djsegal/julia_observer#111]
I'm having a difficult time finding my package under any top packages category on Julia Observer. It is searchable, but I'd like to figure out where it can be found on the charts. Here is the package https://juliaobserver.com/packages/VariantVisualization.

Can I register my package for a specific category? Ideally it would fall under "Genomics".
https://juliaobserver.com/categories/Genomics

**Comment by djsegal** [comment]
Think this is related to issue djsegal/julia_observer#93?

**Comment by gtollefson** [comment]
@djsegal I've posted an issue on Julia.jl as you recommended. Thank you!
