### ISSUE TITLE
Counting unregistered Julia packages

### ISSUE THREAD

**Issue by ScottPJones** [djsegal/julia_observer#117]
I think it would be a useful improvement (to this already very nice package!), to also add unregistered Julia packages (which for the most part can be found by searching for package names that end in .jl).
For the reasoning, see the discussion on Discourse: https://discourse.julialang.org/t/juliaobserver-com-a-package-browsing-tool-for-julia/1685/7?u=scottpjones

**Comment by djsegal** [comment]
PR djsegal/julia_observer#7 should resolve this. I'll try to launch it sometime in the next few nights
