### ISSUE TITLE
Package list not working

### ISSUE THREAD

**Issue by eyglys** [djsegal/julia_observer#126]
Package list isn't available

**Comment by djsegal** [comment]
Related to:
+ https://github.com/djsegal/julia_observer/issues/124

Put a bandaid on it earlier, but apparently it fell off. 

// will actually fix it this time!

**Comment by djsegal** [comment]
Just pushed these changes:

+ https://github.com/djsegal/julia_observer/commit/7f24e24f6eded85d6d4b3d837ac3ad24ece01a67

-----

Hopefully the pipeline works with it on the next 6-hour cycle!

// maybe should add a big red button in the future for admin restarts

**Comment by djsegal** [comment]
Optimistically going to close this (:

// just let me know if it happens again and we can look into it further!
