### ISSUE TITLE
juliaobserver.com broken?

### ISSUE THREAD

**Issue by murrayE** [djsegal/julia_observer#178]
Visiting juliaobserver.com gives a "Whops...Something went wrong" error.

**Comment by younes-io** [comment]
Yes, and this also seems abandoned ..; ?

**Comment by djsegal** [comment]
Apologies. Should be back up now. Will update DB shortly as well

**Comment by younes-io** [comment]
@djsegal I don't think this is resolved, it's down

![image](https://github.com/djsegal/julia_observer/assets/3153107/bade6fdf-3a49-4e72-adad-ecf3a522394b)
