### ISSUE TITLE
GR package unknown

### ISSUE THREAD

**Issue by jheinen** [djsegal/julia_observer#2]
The `GR` package is listed in the pull-down _search_ menu, but it does **not** appear anywhere. Instead, the _Julia observer_ always displays information about `GracePlot` when searching for `GR`.

**Comment by djsegal** [comment]
Is it still missing?

Not ignoring your concern, just trying to tackle how to resolve it

**Comment by jheinen** [comment]
It is listed in the pull-down search menu:

<img width="403" alt="screen shot 2017-01-19 at 19 19 54" src="https://cloud.githubusercontent.com/assets/5718244/22119590/75456f7e-de7c-11e6-8a5c-ccf0143962bb.png">

... but when i select it, I get an error:

<img width="545" alt="screen shot 2017-01-19 at 19 20 07" src="https://cloud.githubusercontent.com/assets/5718244/22119625/9b786e12-de7c-11e6-8f6f-393636980d91.png">

**Comment by jheinen** [comment]
Thanks - now it works!

**Comment by jheinen** [comment]
Right now, it is **not** working !?

**Comment by djsegal** [comment]
I added some debugging tools that you can use (i.e. https://juliaobserver.com/logs). 

Hopefully that will help us get to the bottom of it.

**Comment by jheinen** [comment]
Right now, it works again. I can't explain ...

**Comment by djsegal** [comment]
Haha. I think it's a server/api-polling problem.

I'm still trying to determine the underlying cause, so we can efficiently solve it.

**Comment by djsegal** [comment]
I just upped the box specs for the server.

Kind of just covered up the problem instead of solving it, though.

-------

next time we face it, hopefully better tools are implemented
