### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by djsegal** [djsegal/julia_observer#24]
> The main thing I want is package search, but Julia Observer seems to miss a lot of relevant packages. (Search is a hard problem.) For example, if I type interpolation into the search bar, it misses packages that show up on the first page of a general google search. (Dierckx, ApproxFun, etc.)

- @timholy

**Comment by timholy** [comment]
I also should mention that I was reminded of the existence of http://genieframework.com/packages, which does seem to focus on the problem of search. Perhaps some collaboration is in order?

**Comment by djsegal** [comment]
Just finished adding advanced search using the [pg_search gem](https://github.com/Casecommons/pg_search).

Having said that, it's slower than molasses. And `ApproxFun` won't ever get caught without machine learning due to no word similar to `interpolation` being found in its:

+ `name`
+ `description`
+ `readme`

-----------

Do you have any insight into this matter? (short of saying to use `elasticsearch`)

The code for the current package searching can be found [here](https://github.com/djsegal/julia_observer/blob/23261e9d3e5a70eacf04130ce763ffb600ffa304/app/models/package.rb#L24-L38)

**Comment by djsegal** [comment]
**edit:** might be an indexing issue. ill check this out tomorrow (i.e. need to index readme in db)

**Comment by djsegal** [comment]
Resolved by commits from 4/6/17 - 4/9/17

@timholy, tell me if you have any suggestions

-----------

one annoyance is that:

+ autocomplete uses shallow search (no `readme` checking)
+ real search (when you press enter) uses deep search // i.e. with `readme` search

this was needed because people don't like waiting seconds for autocomplete
