### ISSUE TITLE
Require graphs for package versions

### ISSUE THREAD

**Issue by djsegal** [djsegal/julia_observer#25]
> I would like to see the context of the package, shown in a graph, with its ancestors (things it depends on), and it's decendants (things) that depend on it, shown.
> (Probably with links).
> 
> Example shown below: (Enjoy the aweful inkscape skillz)
> 
> ![](https://cdn-standard2.discourse.org/uploads/julialang/original/1X/c6c23e921fb806d1dbf4af105171a53adce181d5.png)
> 
> Potentially links could be shown between other nodes in the graph (which I think would be interesting).
> (This would be the induced_graph between the set of ancestors unioned with the set of decedents)
> 
> I think if proper graph layour was used this would look a lot better.
> 
> The point of this view is to have a good idea of what would break if a package broke, and what breaking would break this package etc, and to generally see where the package lays in the ecosystem

- @oxinabox

**Comment by djsegal** [comment]
@oxinabox, this is live (w/ commits from 4/8/17 - 4/9/17)

// for example, see [NearestNeighbors](https://juliaobserver.com/p/NearestNeighbors.jl)

-----

No graphics support. Just two lists on package#show pages: 

+ `requires:`
+ `used by:`

What do you think?

**Comment by oxinabox** [comment]
That is cool.
I think a graph is better, but it might get too large?
Particularly with all the unregistered packages shown.
It would be nice if this showed direct vs indirect dependence some how, a graph would do that implicitly.

**Comment by djsegal** [comment]
> I think a graph is better, but it might get too large?

My thinking is it would be slow and would cause too much headache for not enough payoff.

> Particularly with all the unregistered packages shown.

I probably should have this go with the checkbox in settings (see issue djsegal/julia_observer#28)

> It would be nice if this showed direct vs indirect dependence some how, a graph would do that implicitly.

I have `direct` vs `indirect` saved in the db. Just tell me how you want to distinguish the two in a list and I'm all onboard. (see issue djsegal/julia_packages#149)

// maybe have direct first followed by indirect. and either indirect or direct are shaded grey(?)
