### ISSUE TITLE
Julia.jl is considered used by everything, but it is not a package at all

### ISSUE THREAD

**Issue by oxinabox** [djsegal/julia_observer#27]
Julia.jl is not a package.
It is a nice curated list of julia packages.

But it is listed in the require section for nearly everything

julia shows up in the REQUIRE file as the julia version requirement.

https://juliaobserver.com/packages/Julia

**Comment by djsegal** [comment]
I agree with this. I'll make sure to change it

**Comment by djsegal** [comment]
Fixed by: https://github.com/djsegal/julia_observer/commit/46cfe57e025b1aaca8f303d294683cc780628405
