### ISSUE TITLE
Distinguish direct requirements from indirect ones on package#show pages

### ISSUE THREAD

**Issue by djsegal** [djsegal/julia_observer#29]
see issue #25

**Comment by oxinabox** [comment]
Maybe indicate it with a `*` with an explianation ("* indirect dependency") below (and similar for "*indirect requirement" saying below what that means.
Bonus points if the there is some way to find the path for the indirect ones.

(Maybe mouse-over, or a tool tip?)

**Comment by djsegal** [comment]
Fixed by: https://github.com/djsegal/julia_observer/commit/23afcde801a1259ab1aa24da762e344bd7495f4c
