### ISSUE TITLE
Blog link not working

### ISSUE THREAD

**Issue by blegat** [djsegal/julia_observer#3]
On [my profile](https://juliaobserver.com/users/blegat), the blog link is missing the "http://" hence the link is not working, it points to "https://juliaobserver.com/users/perso.uclouvain.be/benoit.legat". However, on [my GitHub profile](https://github.com/blegat), the "http://" is present.

**Comment by djsegal** [comment]
Very similar to: https://github.com/djsegal/julia_observer/commit/5c85e5be55b832f7e91947cdd1c840b41554b553

I'll fix this within the next couple days

**Comment by djsegal** [comment]
Fixed w/ https://github.com/djsegal/julia_observer/commit/382e4afe0fcc0fa3f4c6ecf08058a043964ebc7b
