### ISSUE TITLE
Make Requires and Used-by list show a count?

### ISSUE THREAD

**Issue by oxinabox** [djsegal/julia_observer#36]
The Requires and Used-by lists are super cool and useful to me, just like I hoped.
It would enhance them if the size of the list was shown, eg in the heading.
This would make it easy to identify if a package is going to haul down half the ecosystem when I install it.

I have created a very quick mockup: (prob should be right aligned)

![image](https://cloud.githubusercontent.com/assets/5127634/25786110/be7a03d6-33c1-11e7-8a66-250a9770fa16.png)

**Comment by djsegal** [comment]
How about if it was just "10 | _21_" in the top right corner?

It might be confusing the first time you see it, but I think it's still pretty easy to grasp

**Comment by oxinabox** [comment]
what ever you think is best
Can always stick a tool tip on it.

**Comment by djsegal** [comment]
I like where you're going with that

**Comment by djsegal** [comment]
resolved by: https://github.com/djsegal/julia_observer/commit/17a3f60c518cdbdb6aaf99b12a3ec702cfcc40e1
