### ISSUE TITLE
Mustache package webpage layout is broken

### ISSUE THREAD

**Issue by Kissaki** [djsegal/julia_observer#47]
The [page layout of the Mustache package](https://juliaobserver.com/packages/Mustache) is completely broken.

The right sidebar area is empty, and the sidebar contents are wrongly layouted in the package description area.

The bottom info panels are at the bottom, but completely break their layout.

![image](https://user-images.githubusercontent.com/93181/44950730-c4ab2500-ae4f-11e8-837a-f1baa6bf01a7.png)
![image](https://user-images.githubusercontent.com/93181/44950733-d68cc800-ae4f-11e8-979e-d988b2e71e99.png)

I checked some other packages, namely top trending ones, and those layouts are fine.

**Comment by djsegal** [comment]
The real way to solve it is to get the readme.html, not the readme.md (from the github api)

// then just render the html onto the page

------

This is what I did on JuliaPackages:
- https://juliapackages.com/p/mustache

Probably won't make the fix on this project though :/
