### ISSUE TITLE
Add GMT.jl to Earth Sciences and Plotting categories.

### ISSUE THREAD

**Issue by joa-quim** [djsegal/julia_observer#48]
Please, add [GMT.j](https://github.com/GenericMappingTools/GMT.jl)l to the ``Graphical Plotting`` and ``Earth Sciences`` categories. It's currently listed under ``GIS`` which in fact the GMT program is not.

**Comment by joa-quim** [comment]
Bump?

**Comment by djsegal** [comment]
Sorry for the delay, this is a problem in Julia.jl -- see: 

+ https://github.com/svaksha/Julia.jl/blob/master/db.csv#L593

`Earth-Science,[GIS](https://en.wikipedia.org/wiki/Geographic_information_system),GMT.jl,https://github.com/joa-quim/GMT.jl,"is a package containing Julia bindings for the Generic Mapping Tools Library, a.k.a libgmt - a set of libraries tht allows manipulating geographic and Cartesian data sets (including filtering, trend fitting, gridding, projecting, etc.) and producing Encapsulated PostScript File (EPS) illustrations ranging from simple x-y plots via contour maps to artificially illuminated surfaces and 3-D perspective views."`

-------

There it is listed as a GIS. I just scrape their data, so you'd need to make a PR to them. 

// should have said that sooner :/

**Comment by djsegal** [comment]
it is on juliapackages.com:
+ https://juliapackages.com/p/gmt

// just reopen if you need anything!
