### ISSUE TITLE
Tooltip for number of Requires does not work in firefox

### ISSUE THREAD

**Issue by oxinabox** [djsegal/julia_observer#49]
I was testing out https://github.com/djsegal/julia_observer/issues/36
And it wasn't working.

So I went and checked the page source, to make sure it was there;
and indeed it was there in the source.
But it never showed up.

So I investigated deeper.
Here are my conclusions:

- **Firefox 53.0.3:** tooltip does not show up
- **Edge 40.15063.0.0:** Work perfectly
- **Opera 45.0.2552.888** Work perfectly
- **Chrome 58.0.3029.110** Works, however the background color of the tooltip is much darker than in Edge or Opera.

**Comment by djsegal** [comment]
Can you send a screenshot for the chrome being darker than edge?

Also, the firefox issue is very interesting! I have a lead on it, but I'll look into it further now that I know it exists

**Comment by djsegal** [comment]
Should be fixed by: https://github.com/djsegal/julia_observer/commit/ff3a0eedb6d684a83947d37ae4a3176d071c8e22

**Comment by oxinabox** [comment]
Yes, yes it is.
