### ISSUE TITLE
Theme selection 

### ISSUE THREAD

**Issue by silenj** [djsegal/julia_observer#49]
Hi, I am amazed by how well julia_observer is actually presenting the package infrastructure. Still I would like to know how to modify the display theme and in particular the colors. The default is quite hard to read. Can this be done and if then how? I tried on Firefox and Chrome and neither gave good results.

**Comment by djsegal** [comment]
Probably won't be adding theming to julia observer

if you have any ideas for [juliapackages.com](http://juliapackages.com/), feel free to raise an issue [there](https://github.com/djsegal/julia_packages/issues)!

// this could include theming (:
