### ISSUE TITLE
Counting unregistered Julia packages

### ISSUE THREAD

**Issue by ScottPJones** [djsegal/julia_observer#5]
I think it would be a useful improvement (to this already very nice package!), to also add unregistered Julia packages (which for the most part can be found by searching for package names that end in .jl).
For the reasoning, see the discussion on Discourse: https://discourse.julialang.org/t/juliaobserver-com-a-package-browsing-tool-for-julia/1685/7?u=scottpjones

**Comment by djsegal** [comment]
Would something like this query be kosher?
[
 q = .jl + 
in:name + 
language:julia +
stars:>10 +
pushed:>2017-01-01
](https://api.github.com/search/repositories?q=.jl+in:name+language:julia+stars:%3E10+pushed:%3E2017-01-01)

// where the pushed date is something like `6.months.ago`

**Comment by ScottPJones** [comment]
I think that might be a bit high, for the number of stars, a lot of useful registered packages only get a few stars (for example, we use https://github.com/nolta/ICU.jl at work, and that only has 7 stars).
Maybe 5 stars?
Is it possible to have the pushed part of the query to be something like the date of the last Julia release, or if that is < 2 months, the date of the previous Julia release?  It's been over 6 months since v0.5 came out, but since v0.6 isn't out yet, you'd be penalizing the packages that updated for v0.5 immediately (or even before v0.5 was officially released, if they fixed any issues after the first beta release or RC release)

Thinking about that, that might be a good metric to use on registered packages as well, there are many moribund registered packages out there unfortunately.

**Comment by KristofferC** [comment]
I think by default unregistered packages should not be shown. (and to show I am not biased, my package with way most stars is not registered) :P.

**Comment by ScottPJones** [comment]
That's fine (to have the default be that unregistered packages not be shown), I just wanted to have these packages made discoverable (I only found things like Benchmarks.jl by word of mouth, and Juliaobserver will make it a lot easier to find them)

**Comment by JeffreySarnoff** [comment]
+1 available via active selection, not seen by default

I suggest have nonregistered packages orderable by stars, and orderable by recency and each have a settable cutoff that can be set to 0+ stars / nn months.  I have seen emulation-worthy and highly useful unregistered packages with no stars.  Some I use; the good ones are hard to find without the tooling you provide. And it becomes a better star-catcher.

**Comment by djsegal** [comment]
@JeffreySarnoff 
+ my only concern with this is number of api requests used. Right now, I guess it's only ~40 initial hits so it's not that bad (plus the 3N+ subsequent fetches)
+ star minimum and date range querying should be another issue

**Comment by JeffreySarnoff** [comment]
@djsegal I expect the api requests will grow proportionally with its spreading awareness. :grin:

**Comment by djsegal** [comment]
wow there buddy...

i just don't think we should be storing 500 unpublished packages that havent been updated in 9 months with 0 stars

over time when the api fetcher becomes more developed we can reduce constraints and increase the breadth of unpublished packages

you're just asking for premature optimization and nice-to-haves at this point

--------

however, i do like the idea for star minimums and date ranges. i would appreciate an issue for that

**Comment by djsegal** [comment]
This requires caching api requests (to fully satisfy all requirements). 

Will get to it within the month.

**Comment by djsegal** [comment]
Hi all,

This should be resolved by: 
+ https://github.com/djsegal/julia_observer/commit/130b3e2896ccc71e9c7482ba2f2b8e6ec4d33dd1 
+ https://github.com/djsegal/julia_observer/commit/199d124b4da12bb64e1c9faf8ea32e3c43e45199
+ and a few more commits from this weekend

----------

To view unregistered packages,

+ click on dropdown in navbar
+ select settings
+ click checkbox with "Include Unregistered Packages" next to it
+ click "Save changes"

Tada, you can now view almost all 3000+ Julia packages living on github

----------

Also, closing this issue.

Feel free to open new ones (and/or comment on this one)

Caching ain't easy. There might be a few weird bugs walking around

**Comment by ScottPJones** [comment]
I just checked it out, but in the "TOP" view, it didn't show my `StringUtils` package (with 16 stars) ranked with the other packages with 16 stars (although it did show it, via "Search").
Also, when I tried the "A-Z" view, it consistently hangs after I scroll down to around item 870 (processor starts running full blast, shows "Please wait..." at bottom of page).

**Comment by djsegal** [comment]
@ScottPJones 

+ the reason `StringUtils` wasn't in the list was because you have to check the `include unregistered` box in settings
+ the reason it showed up in search was because i didn't think i needed the filtering there. now that you says this, though, maybe I should filter everything to make it more obvious (a new issue would be recommended)

lastly, i think the `please wait...` is related to throttling. im able to reproduce this, so hopefully ill fix it soon (a new issue for this would be nice too, because these aren't really related)

**Comment by ScottPJones** [comment]
Yes, I did check (and save) the `include unregistered` setting.  Some of my other unregistered packages showed up in the "NEW" list, it was only that the "TOP" list didn't have the one with 16 stars. The "A-Z" list had all of them (this time I was able to get all of them).

**Comment by djsegal** [comment]
Ok. That is really interesting! I'll look into it

**Comment by djsegal** [comment]
@ScottPJones 

I removed throttling w/  https://github.com/djsegal/julia_observer/commit/912fd0eb740a20da9d5274052f1665403eacf4c4

I don't know how to reproduce the 16 star bug you're talking about. Even if you clicked the back button it should have reloaded with the cookie. 

+ Is it not at the 337 slot? 
+ Maybe earlier it had 15 or 17 stars?

**Comment by ScottPJones** [comment]
Hmmm, now it has shown up, a day later!  Is there some cache that is only getting updated every so often?
Anyway, it seems to be working now - so time to close this little mystery!

**Comment by djsegal** [comment]
@JeffreySarnoff there is no date restriction anymore for the github ingestion

We're now up to 3854 repos! 😄
