### ISSUE TITLE
Used by block with too many packages doesn't show checkbox

### ISSUE THREAD

**Issue by oxinabox** [djsegal/julia_observer#50]
Consider [Compat](https://juliaobserver.com/packages/Compat).
I checked Firefox and Chrome.

![image](https://user-images.githubusercontent.com/5127634/27265279-04f2e61a-54c5-11e7-829d-647a5903f6f1.png)

Looks like if no Requires checkbox is needed, then even if it is needed, the Used-by one doesn't show up.
(The reverse is not true though. if no Usedby is needed, then the Requires still shows up, and the Used-by doesn't)

**Comment by oxinabox** [comment]
Actually, it might *just* be Compat that is broken like this.
I can't find any other packages that don't have any Requires and do have some Used-bys.

**Comment by djsegal** [comment]
The checkboxes only appear if there are indirect dependencies/required_bys

**Comment by djsegal** [comment]
The checkboxes only appear if there are indirect dependencies/required_bys

// and the lists have to have packages to begin with

----------

is it confusing that the checkboxes aren't there when they don't need to be?

**Comment by djsegal** [comment]
@oxinabox, your issue actually probably stems from:

https://github.com/djsegal/julia_observer/blob/master/app/views/packages/_require.html.erb#L13

-------

This is because Compat is used by so many libraries. 

In the end only 100 (direct requires) get used // and therefore no indirect dependencies or checkbox get shown

how do you think this should be handled?

**Comment by oxinabox** [comment]
>how do you think this should be handled?

Would it break something to just show all of them?
It is less than 5000 packages.
So it means sending at extreme most 200Kb of data.

If all can't be shown, then that makes showing the UsedBy numbers even more important.
Maybe they should not be, behind a tool-tip at all.
I'm not sure about this.
I am no UX dev.


>is it confusing that the checkboxes aren't there when they don't need to be?
Maybe.
See again, I know little of good UX.

What I know is that for understanding how the ecosystem works out,
I wish to compare the counts for Compat.jl, vs other commonly used packages,
like BinDeps.jl, Requires.jl and MacroTools.jl

**Comment by djsegal** [comment]
Ok. I'll make some change to handle highly used packages.

And then we can move forward from there

**Comment by djsegal** [comment]
> Would it break something to just show all of them?

5000 packages is probably too many for a page // don't really want anything with that long of a scroll?

--------

The fix I added shows the user that there are max packages by starting w/ the checkbox filled in

(and it shows the correct stats now, too) // see commit: https://github.com/djsegal/julia_observer/commit/579317876e6d61475bd37afa9ebc7c458c4a7abf

Tell me what you think! 

**edit:** 

+ also, do you want a setting that allows you to change the number of packages
+ (so you can have `5000` if you want)

**update:**

i also fixed that annoying bug where the tooltip would flicker (woo!)

**Comment by oxinabox** [comment]
Working

>  also, do you want a setting that allows you to change the number of packages
    (so you can have 5000 if you want)

It seems like a sensible option might be to have a link as the bottom element of the list saying:
"show more? (4900) other packages"

Then you click it and it shows the full list.

**Comment by djsegal** [comment]
Ask and you shall receive.

`Show more` button now active

**Comment by djsegal** [comment]
@oxinabox, it was cool to close this right?

are you happy with how this turned out?

**Comment by oxinabox** [comment]
Looks good, except rather than saying "View Dependent Packages",
it needs to give some indication that not all have been shown.

Eg:
"List Truncated to 100 elements. View All Dependent Packages",
