### ISSUE TITLE
Raise the character limit for descriptions

### ISSUE THREAD

**Issue by crbinz** [djsegal/julia_observer#6]
Really nice thing you've built here. My suggestion is to not cut off the descriptions in list view. Right now, 6 of the 8 packages "above the fold" in the "Hot" category are cut off for me (e.g. `A julia package for creating simple psychophysi...`).

**Comment by djsegal** [comment]
I see where you're coming from, but I think some cutoff is required.

Do you have some character limit in mind that you think would work well?

**Comment by crbinz** [comment]
I agree that a cutoff is probably needed. I don't know that I have a good answer for what it should be, besides a different, higher arbitrary number (80?)

**Comment by djsegal** [comment]
resolved w/: https://github.com/djsegal/julia_observer/commit/1bc000767588735c5a468759c04de2775f6b7e14
