### ISSUE TITLE
RSS for new packages

### ISSUE THREAD

**Issue by dfdx** [djsegal/julia_observer#8]
As discussed on the [forum][1] I suggest to integrate RSS for tracking new registered packages to juliaobserver.com. Three ways to integrate are:

1. Add a `<link>` to a service provided by me (coming soon) to HTML template.
2. Call my API from server side. 
3. Rewrite the code to Ruby and provide RSS without additional costs. 

The code is pretty simple and boils down to 1) calling GitHub API; 2) parsing pull requests; 3) generating XML file (you can check my version [here][2], ignore SQL stuff for now). If it looks as an easy target for you, rewriting to Ruby seems the most "organic" way to go. On the other hand, my service is almost done, so it's up to you how to decide. 

[1]: https://discourse.julialang.org/t/what-about-a-service-that-tracks-every-new-registered-package/1575/19
[2]: https://github.com/dfdx/PackageTracker.jl/tree/master/src

**Comment by djsegal** [comment]
How would this feature work with [issue#5](https://github.com/djsegal/julia_observer/issues/5)?

Would a sweep of all unregistered packages not catch everything found in your feed?

-------

**edit:** 
+ i'm just trying to get to the bottom of what needs to get done
+ do people want a new route that serves as a news feed for up-and-coming packages?

**Comment by dfdx** [comment]
Not quite. The feed has a different purpose than the package search. The package search is intended for people who want to find packages by particular criteria like topic, number of stars, etc., be they registered or not. 

The aim of the feed is to post updates about newly registered packages, a kind of news about Julia package ecosystem. We could, of course, search for every newly available package ending with `.jl`, but I believe many of them aren't mature enough, "die" quickly or not intended for public usage at all (I have a bunch of such packages myself). Package registration, on the other hand, at least means "this stuff might be interesting for someone except the author".

**Comment by dfdx** [comment]
In fact, I'm not even sure that this feed should be a part of Julia Observer. My motivation here is that:

1. One service is better than two. More convenient for users, better for search engine optimization and all such stuff. 
2. Name "julia observer" seems to correlate with the service of tracking of new packages.

However, I never asked what you think about it, and you may have a very different vision, so please don't hesitate to share it.

**Comment by djsegal** [comment]
Let me think about it some more. I think there might be a way to do it by making a `news` model that can hold onto packages.

Can you post an example rss feed?

**Comment by dfdx** [comment]
Here's what I've got for RSS with the latest version of my package tracker: 

http://pastebin.com/pSZpyLCp

You can also run the tracker locally using [these instructions](https://discourse.julialang.org/t/what-about-a-service-that-tracks-every-new-registered-package/1575/22?u=dfdx).

**Comment by dfdx** [comment]
By the way, Julia package news sounds quite tempting, but except for package updates, what else can get to the news?

**Comment by djsegal** [comment]
just a few things off the top of my head:

+ reddit posts (from [r/julia](https://www.reddit.com/r/julia))
+ popular discourse posts
+ heavy traffic julia issues/pr's
+ new julia blog posts
+ general announcements (julia con proposals, new meetup groups, etc)

**Comment by djsegal** [comment]
Just to start off small, the two things we'll focus on first are:

1) package releases from PRs (grepping on register)
2) reddit posts from r/julia

**Comment by djsegal** [comment]
Got the reddit stuff working. Now moving onto discourse and the PRs.

One question is what query did you use? Would this work:

[q = 
register + 
repo:JuliaLang/METADATA.jl + 
type:pr + 
updated:>=2017-01-01 +
is:merged &
sort=updated
](https://api.github.com/search/issues?q=register+repo:JuliaLang/METADATA.jl+type:pr+updated:%3E=2017-01-01+is:merged&sort=updated)

**edit:** updated query with merged restriction in mind

**Comment by dfdx** [comment]
Here's exactly what I do:

https://github.com/dfdx/PackageTracker.jl/blob/master/src/gh.jl#L29-L40

Essentially, I read the latest 200 merged PRs and filter them by regex `r"^[Rr]egister.*"`. Then I store them to a database for quick retrieval.  

Using a query should work even better, but make sure you ingest only merged pull requests, since some PRs may be declined or stay open for a long time.

**Comment by djsegal** [comment]
Hopefully taken care of with: https://github.com/djsegal/julia_observer/commit/2014e155e1e49108ad60029ac383fb0d150c39a3

Probably testing it over the weekend

**Comment by djsegal** [comment]
@dfdx, is this now working as expected?

// comments on how to view them available: [here](https://discourse.julialang.org/t/what-about-a-service-that-tracks-every-new-registered-package/1575/26?u=djsegal)

----

**edit:** if an rss is truly needed, should I just copy your formatting?
