### ISSUE TITLE
new genomics packages

### ISSUE THREAD

**Issue by phaverty** [djsegal/julia_observer#93]
The GenomicVectors.jl and RLEVectors.jl packages might be of interest to users searching the "Genomics" category.

**Comment by djsegal** [comment]
I think you'd have to make an issue at?

+ https://github.com/svaksha/Julia.jl

**Comment by henselman-petrusek** [comment]
I just visited https://github.com/svaksha/Julia.jl and for whatever don't see a button to create new issues.  What should future developers do?
